version: "3.8"

services:
  wg-easy:
    environment:
      # ⚠️ Change the server's hostname (clients will connect to):
      - WG_HOST=your.ddns.com

      # ⚠️ Change the Web UI Password:
      - PASSWORD=YourPassword

      # 💡 This is the AdGuard Container's IP Address
      - WG_DEFAULT_DNS=10.8.1.3
      - WG_DEFAULT_ADDRESS=10.8.0.x
      - TZ=Europe/Madrid
    image: weejewel/wg-easy
    container_name: wg-easy
    volumes:
      - ~/docker/wg-easy:/etc/wireguard
    ports:
      - "51820:51820/udp"
      - "51821:51821/tcp"
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    sysctls:
      - net.ipv4.ip_forward=1
      - net.ipv4.conf.all.src_valid_mark=1
    networks:
      vpn:
        ipv4_address: 10.8.1.2

  adguard:
    image: adguard/adguardhome
    container_name: adguard
    environment:
      - TZ=Europe/Madrid
    volumes:
      - ~/docker/adguard/config:/opt/adguardhome/conf
      - ~/docker/adguard/data:/opt/adguardhome/work/data
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "443:443/tcp"
      - "443:443/udp"
      - "8537:8537/tcp"
      - "3000:3000/tcp"
    restart: unless-stopped
    networks:
      vpn:
        ipv4_address: 10.8.1.3

networks:
  vpn:
    ipam:
      config:
        - subnet: 10.8.1.0/24
